# Generated by Django 2.2.2 on 2019-06-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'customer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'employer',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('location', models.CharField(max_length=64, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'formation',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='HobbyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='label')),
                ('icon_class', models.CharField(blank=True, max_length=32, null=True, verbose_name='icon class')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'hobbies category',
                'verbose_name_plural': 'hobbies categories',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('reading', models.BooleanField(verbose_name='reading')),
                ('writing', models.BooleanField(verbose_name='writing')),
                ('speaking', models.BooleanField(verbose_name='speaking')),
            ],
            options={
                'verbose_name': 'language',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='label')),
                ('order', models.IntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name': 'skills category',
                'verbose_name_plural': 'skills categories',
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, verbose_name='label')),
                ('level', models.PositiveIntegerField(blank=True, choices=[(1, 'beginner'), (2, 'intermediate'), (3, 'experienced'), (4, 'expert')], null=True, verbose_name='level')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='my_resume.SkillCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'skill',
                'ordering': ('category', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('location', models.CharField(max_length=32, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('short_description', models.TextField(verbose_name='short description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('nl_after', models.BooleanField(default=False, verbose_name='new line after')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='my_resume.Customer', verbose_name='customer')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='my_resume.Employer', verbose_name='employer')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobs', to='my_resume.Skill', verbose_name='skills')),
            ],
            options={
                'verbose_name': 'job',
                'ordering': ('-start_date',),
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='my_resume.HobbyCategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'hobby',
                'verbose_name_plural': 'hobbies',
                'ordering': ('name',),
            },
        ),
    ]
